### PR TITLE
Improved gcd a little bit, mark where's broken

### PR DESCRIPTION
**Pull request by jywyq**
Small improvement

### CODE REVIEW

**Comment by jywyq** [comment]
I'm not very sure about the logic change in grammar, but from my understanding of the wiki page 
https://en.wikipedia.org/wiki/Shor%27s_algorithm
It says Step 6: If {\displaystyle a^{r/2}\equiv -1({\bmod {N}})}{\displaystyle a^{r/2}\equiv -1({\bmod {N}})}, then go back to step 1. 
Please check again

**Comment by cjoverbay** [comment]
Thanks for the contribution!

The similulator is broken and we know the fix. Essentially complex numbers when squared are supposed to be real, but they aren't in python. So the random voice doesn't know how to deal with the complex numbers. Additionally the state vector becomes slightly unnormalized over time. So we need to add a normalization step.

Thanks for fixing that part of shor's algo!

Also need to add some unit tests once this is running. probably a simple case like 3* 5 =15

**Comment by jywyq** [comment]
I see, will also look into adding unit tests and problems you said in other issues...

**Comment by jywyq** [comment]
Resolved conflict

**Comment by jywyq** [comment]
Do you know where could possibly be wrong about find_period function? Should the problem lie in the circuit building, or in the simulator?

I tried a in [2,4,7,8,11,13] with N=15, and all outputs gives {'00000': 1024} which is obviously run.

**Comment by jywyq** [comment]
After reading through the code, I believe the find_period function is not completed yet, but why's there not an Issue for this? XD

**Comment by shordev** [comment]
@jywyq Yep there are a lot of incomplete things in the library at the moment!

Will make a ticket if you are interested in completing that that would be awesome

**Pull request merged**
